<?php

require_once 'classes/Dependency.php';
require_once 'classes/Module.php';
require_once 'classes/JSONLoader.php';
require_once 'classes/I18N.php';

use \JSONInstaller\Dependency;
use \JSONInstaller\Module;
use \JSONInstaller\JSONLoader;
use \JSONInstaller\I18N;

/**
 * JSON Installer Module
 *
 * A tool for common used setup processes
 *
 * Copyright 2013 by Pieter Beulque
 *
 * ProcessWire 2.x
 * Copyright (C) 2012 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://processwire.com
 *
 */



class ProcessJSONInstaller extends Process {

    public static function getModuleInfo() {
        return array(
            'title' => 'JSON Installer',
            'summary' => I18N::get('Run JSON files to create fields, templates and pages and install Plugin Modules'),
            'version' => 30,
            'author' => 'Pieter Beulque',
            'permission' => 'page-edit',
        );
    }

    const pageName = 'json-installer';
    const confirmParam = 'confirm';
    const emptyModuleName = '"EMPTY MODULE NAME"';

    /**
     * Array containing all installable modules
     */
    protected $installableModules;
    protected $jsonLoader;

    /**
     * The base URL for the module
     */
    protected $url;
    protected $title;

    public function init() {
        parent::init(); // required

        $this->jsonLoader = JSONLoader::create();
        $this->url = wire('pages')->get('template=admin, name=' . self::pageName)->url;

        $moduleInfo = self::getModuleInfo();
        $this->title = $moduleInfo['title'];
    }

    public function ___execute() {
        $table = $this->modules->get('MarkupAdminDataTable');
        $config = $this->config;

        $headerColumns = array(
            I18N::get('name'),
            I18N::get('description')
        );

        if ($config->advanced) {
            $headerColumns[] = I18N::get('also un-/installs');
            $headerColumns[] = I18N::get('install');
            $headerColumns[] = I18N::get('uninstall');
        } else {
            $headerColumns[] = I18N::get('also installs');
            $headerColumns[] = I18N::get('action');
        }

        $table->headerRow($headerColumns);

        $installableModules = $this->jsonLoader->getModules();

        foreach ($installableModules as $key => $module) {

            $jsonDependencies = array();
            foreach ($module->jsonDependencies as $jsonDependency) {
                if(isset($jsonDependency->name)) {
                    $jsonDependencies[] = $jsonDependency->name;
                }
            }

            if(count($jsonDependencies) > 0) {
                $alsoInstalls = implode(', ', $jsonDependencies);
            } else {
                $alsoInstalls = '';
            }

            $contentColumns = array(
                $module->name,
                $module->description,
                $alsoInstalls,
                I18N::get('Install') => $this->url . 'install/' . $key
            );

            if ($config->advanced) {
                if ($module->hasDeletableItems($forceDryRun = true)) {
                    $contentColumns[I18N::get('Uninstall')] = $this->url . 'uninstall/' . $key . '/' . self::confirmParam;
                } else {
                    $contentColumns[] = 'n/a';
                }

            }

            $table->row($contentColumns);
        }

        // $actionName = ;
        $table->action(array(I18N::get('Export site') => $this->url . 'export/'));

        $out = $table->render();
        return $out;
    }

    protected function addFolderToZip ($dir, $zip) {
        $actualDir = $dir;
        $dirName = substr($dir, strpos($dir, '/site/') + 1);

        if ($dh = opendir($actualDir)) {
            $zip->addEmptyDir($dirName);

            while (($file = readdir($dh)) !== false) {
                if ($file === '.' || $file === '..' || $file === '.DS_Store') continue;

                if (!is_file($actualDir . '/' . $file)) {
                    if ($file !== '.git') {
                        $this->addFolderToZip($actualDir . '/' . $file, $zip);
                    }
                    continue;
                }

                $zip->addFile($dir . '/' . $file, $dirName . '/' . $file);
            }
        }
    }

    protected function buildZipArchive() {
        $directories = array('site/install', 'site/modules', 'site/templates');
        $zip = new ZipArchive();

        $filePath = $this->config->paths->root . 'site/assets/site-export-' . date('Y-m-d') . '.zip';

        if ($zip->open($filePath, ZipArchive::CREATE) === TRUE) {
            foreach ($directories as $dir) {
                $this->addFolderToZip($this->config->paths->root . $dir, $zip);
            }

            $zip->close();
        }

        return $filePath;
    }

    public function ___executeExport() {

        $this->breadcrumbs->add(new Breadcrumb($this->url, $this->title));
        $this->fuel->set('processHeadline', I18N::get('Export'));

        $export = $this->modules->get('ProcessExportProfile');

        if (!$export) {
            $this->error(I18N::get('You need the ProcessExportProfile module for this.'));
            return $this->___execute();
        }

        if (!$export->___executeRemove()) {
            $this->error(I18N::get('Something went wrong cleaning a leftover install'));
        }

        if (!$export->___executeDump()) {
            $this->error(I18N::get('Something went wrong executing the database dump'));
        }

        if (!$export->___executeCopy()) {
            $this->error(I18N::get('Something went wrong copying your files'));
        }

        $filename = $_SERVER['HTTP_REFERER'];
        $filename = substr($filename, strpos($filename, '//') + 2);
        $filename = substr($filename, 0, strpos($filename, '/admin/'));
        $filename = str_replace(array('.', '/'), '-', $filename);

        $file = $this->buildZipArchive();

        header('Content-Type: application/zip');
        header('Content-Transfer-Encoding: Binary');
        header('Content-disposition: attachment; filename="export-' . $filename . '-' . date('Ymd') . '.zip' . '"');
        readfile($file);
    }

    public function installModule($name) {
        if (!$this->jsonLoader) {
            $this->jsonLoader = JSONLoader::create();
        }

        $module = $this->jsonLoader->getModule($name);

        $altName = $name ? $name : self::emptyModuleName;
        $exceptionMessage = I18N::get('Module %s does not exist.', $altName);

        if ($module) {
            $module->install();
        } else {
            throw new WireException($exceptionMessage);
        }

        return $module;
    }

    public function uninstallModule($name, $dryRun = false) {
        $module = $this->jsonLoader->getModule($name);

        $altName = $name ? $name : self::emptyModuleName;
        $exceptionMessage = I18N::get('Module %s does not exist.', $altName);

        if ($module) {
            $module->uninstall($dryRun);
        } else {
            throw new WireException('Module ' . $altName . ' does not exist.');
        }

        return $module;
    }

    /**
     * Called when the URL is this module's page URL + "/install/?:name/"
     */
    public function ___executeInstall() {
        try {
            $module = $this->installModule($this->input->urlSegment(2));
        } catch (WireException $e) {
            $this->error($e->getMessage());
            return $this->failOutput();
        }

        $this->message(I18N::get('Succesfully installed or updated %s', $module->name));

        $skippedItems = Module::getAllSkippedItems();
        if ($skippedItems) {
            $this->error(I18N::get('Some items were skipped'));
        }

        $headline = I18N::get('Installed %s', $module->name);

        $this->fuel->set('processHeadline', $headline);

        $this->breadcrumbs->add(new Breadcrumb($this->url, $this->title));

        $outputTemplate= self::getTemplate('install');
        $outputTemplate->setArray(array(
            'dependenciesHeadline' => I18N::get('Installed dependencies of'),
            'fieldsHeadline'       => I18N::get('Created or edited fields of'),
            'templatesHeadline'    => I18N::get('Created or edited templates of'),
            'pagesHeadline'        => I18N::get('Created or edited pages of'),
            'skippedItemsHeadline' => I18N::get('Skipped items'),

            'headline'             => $headline,
            'skippedItems'         => $skippedItems,
            'modules'              => Module::$installedModules
        ));

        return $outputTemplate->render();
    }

    /**
     * Called when the URL is this module's page URL + "/uninstall/?:name/"
     */
    public function ___executeUninstall() {
        $name = $this->input->urlSegment(2);
        $confirm = $this->input->urlSegment(3);

        if($confirm === self::confirmParam) {
            return $this->confirmUninstall();
        }

        try {
            $this->breadcrumbs->add(new Breadcrumb($this->url, $this->title));

            $module = $this->uninstallModule($this->input->urlSegment(2));
            $headline = I18N::get('Uninstalled %', $module->name);
            $this->fuel->set('processHeadline', $headline);

            $outputTemplate= self::getTemplate('uninstall');
            $outputTemplate->setArray(array(
                'dependenciesHeadline'       => I18N::get('Dependencies deleted of'),
                'fieldsHeadline'       => I18N::get('Fields deleted of'),
                'templatesHeadline'    => I18N::get('Templates deleted of'),
                'pagesHeadline'        => I18N::get('Pages deleted of'),
                'notInstalledHeadline' => I18N::get('not installed, skipping'),

                'headline' => $headline,
                'modules' => Module::$uninstalledModules
            ));

        } catch (WireException $e) {
            $this->error($e->getMessage());
            return $this->failOutput();
        }

        return $outputTemplate->render();
    }

    /**
     * Called when the URL is this module's page URL + "/confirmuninstall/?:name/"
     */
    protected function ___confirmUninstall() {
        $this->breadcrumbs->add(new Breadcrumb($this->url, $this->title));

        $name = $this->input->urlSegment(2);

        $module = $this->uninstallModule($name, $dryRun = true);

        $headline = I18N::get('Confirm uninstallation of %s', $module->name);
        $isNotInstalledYet = !$module->hasDeletableItems($forceDryRun = false);

        $this->fuel->set('processHeadline', $headline);

        if (!$isNotInstalledYet) {
            $this->message(I18N::get('This feature is experimental.'));
            $this->message(I18N::get('The uninstall process will try to delete all pages, templates and fields defined in this module json, so if you included directives to merely modify existing pages, templates or fields, you should add a "prefab" property to each of those and set it to "true".'));
            $this->message(I18N::get('Nothing will be deleted until you click the "Uninstall!" button below.'));
        }

        $outputTemplate= self::getTemplate('uninstall');
        $outputTemplate->setArray(array(
            'dependenciesHeadline'       => I18N::get('Dependencies to be deleted of'),
            'fieldsHeadline'       => I18N::get('Fields to be deleted of'),
            'templatesHeadline'    => I18N::get('Templates to be deleted of'),
            'pagesHeadline'        => I18N::get('Pages to be deleted of'),
            'notInstalledHeadline' => I18N::get('not installed, skipping'),

            'headline' => $headline,
            'modules' => Module::$dryRunUninstalledModules,
            'isNotInstalledYet' => $isNotInstalledYet
        ));

        $out = $outputTemplate->render();

        if (!$isNotInstalledYet) {
            $button = $this->modules->get('InputfieldButton');
            $button->href = $this->url . 'uninstall/' . $name;
            $button->value = I18N::get('Uninstall!');

            $out .= $button->render();
        }

        return $out;
    }

    public function ___failOutput() {
        $outputTemplate = self::getTemplate('fail');
        $this->fuel->set('processHeadline', 'Fail');
        $outputTemplate->setArray(array(
            'headline' => I18N::get('Whoops! Something went wrong')
        ));
        return $outputTemplate->render();
    }

    public function ___install() {
        $page = new Page();
        $page->template = 'admin';
        $page->name = self::pageName;
        $page->parent = $this->pages->get($this->config->adminRootPageID)->child('name=setup');
        $page->process = $this;
        $page->title = 'JSON Installer';
        $page->save();

        $this->message(I18N::get('Created page: %s', $page->path));

        $this->installModule('config');
        $this->message(I18N::get('Ran config installation script'));
    }

    public function ___uninstall() {
        $moduleID = $this->modules->getModuleID($this);
        $page = $this->pages->get('template=admin,process=' . $moduleID . ',name=' . self::pageName);

        if ($page->id) {
            $this->message(I18N::get('Deleting Page: %', $page->path));
            $page->delete();
        }
    }

    protected static function getTemplate($templateName) {
        $file = dirname(__FILE__) . '/templates/' . $templateName . '.php';
        return new TemplateFile($file);
    }

}
