<?php

require_once 'classes/Dependency.php';
require_once 'classes/Module.php';

/**
 * JSON Installer Module
 *
 * A tool for common used setup processes
 *
 * Copyright 2013 by Pieter Beulque
 *
 * ProcessWire 2.x
 * Copyright (C) 2012 by Ryan Cramer
 * Licensed under GNU/GPL v2, see LICENSE.TXT
 *
 * http://processwire.com
 *
 */

class ProcessJSONInstaller extends Process {

    public static $moduleInfo = array(
        'title' => 'JSON Installer',
        'summary' => 'Run JSON files to create fields, templates and pages',
        'version' => 010,
        'author' => 'Pieter Beulque',
        'permission' => 'page-edit',
    );



    public static function getModuleInfo() {
        return self::$moduleInfo;
    }

    const pageName = 'json-installer';
    const breadCrumbTitle = 'JSON222 Installer';

    /**
     * Array containing all installable modules
     */
    protected $installableModules;
    protected $templatePath;
    protected $url;

    private function loadModules() {
        $dir = wire('config')->paths->siteModules . get_class() . DIRECTORY_SEPARATOR . 'modules';
        $tmp = scandir($dir);
        $this->installableModules = array();

        foreach ($tmp as $file) {
            if (strpos($file, '.json') > 0) {
                $json = json_decode(file_get_contents($dir . DIRECTORY_SEPARATOR . $file));
                $this->installableModules[substr($file, 0, -5)] = JSONInstaller\Module::createFromJSON($json);
            }
        }
    }

    public function init() {
        parent::init(); // required
        $this->loadModules();
        $this->templatePath = dirname(__FILE__) . '/templates';
        $this->url = wire('pages')->get('template=admin, name=' . self::pageName)->url;
    }

    public function ___execute() {
        $table = wire('modules')->get('MarkupAdminDataTable');
        $config = wire('config');

        $headerColumns = array(
            'name',
            'description',
            'install'
        );

        if ($config->advanced) {
            $headerColumns[] = 'uninstall';
        }

        $table->headerRow($headerColumns);

        foreach ($this->installableModules as $key => $module) {

            $contentColumns = array(
                $module->name,
                $module->description,
                'Install' => 'install/' . $key
            );

            if ($config->advanced) {
                if ($module->hasDeletableItems()) {
                    $contentColumns['Uninstall'] = 'confirmuninstall/' . $key;
                } else {
                    $contentColumns[] = 'n/a';
                }

            }

            $table->row($contentColumns);
        }

        $table->action(array('Export site' => $this->url . 'export/'));

        $out = $table->render();
        return $out;
    }

    protected function addFolderToZip ($dir, $zip) {
        $actualDir = $dir;
        $dirName = substr($dir, strpos($dir, '/site/') + 1);

        if ($dh = opendir($actualDir)) {
            $zip->addEmptyDir($dirName);

            while (($file = readdir($dh)) !== false) {
                if ($file === '.' || $file === '..' || $file === '.DS_Store') continue;

                if (!is_file($actualDir . '/' . $file)) {
                    if ($file !== '.git') {
                        $this->addFolderToZip($actualDir . '/' . $file, $zip);
                    }
                    continue;
                }

                $zip->addFile($dir . '/' . $file, $dirName . '/' . $file);
            }
        }
    }

    protected function buildZipArchive() {
        $directories = array('site/install', 'site/modules', 'site/templates');
        $zip = new ZipArchive();

        $filePath = wire('config')->paths->root . 'site/assets/site-export-' . date('Y-m-d') . '.zip';

        if ($zip->open($filePath, ZipArchive::CREATE) === TRUE) {
            foreach ($directories as $dir) {
                $this->addFolderToZip(wire('config')->paths->root . $dir, $zip);
            }

            $zip->close();
        }

        return $filePath;
    }

    public function ___executeExport() {
        $export = wire('modules')->get('ProcessExportProfile');

        if (!$export) {
            $this->error('You need the ProcessExportProfile module for this.');
            return $this->___execute();
        }

        if (!$export->___executeRemove()) {
            $this->error('Something went wrong cleaning a leftover install');
        }

        if (!$export->___executeDump()) {
            $this->error('Something went wrong executing the database dump');
        }

        if (!$export->___executeCopy()) {
            $this->error('Something went wrong copying your files');
        }

        $filename = $_SERVER['HTTP_REFERER'];
        $filename = substr($filename, strpos($filename, '//') + 2);
        $filename = substr($filename, 0, strpos($filename, '/admin/'));
        $filename = str_replace(array('.', '/'), '-', $filename);

        $file = $this->buildZipArchive();

        header('Content-Type: application/zip');
        header('Content-Transfer-Encoding: Binary');
        header('Content-disposition: attachment; filename="export-' . $filename . '-' . date('Ymd') . '.zip' . '"');
        readfile($file);
    }

    public function installModule($name) {
        $this->loadModules();

        $module = $this->installableModules[$name];

        if (empty($module)) {
            throw new WireException();
        }

        $module->install();

        return $module;
    }

    public function uninstallModule($name) {
        $this->loadModules();

        $module = $this->installableModules[$name];

        if (empty($module)) {
            throw new WireException();
        }

        $module->uninstall();

        return $module;
    }

    public function confirmModuleUninstallation($name) {
        $this->loadModules();

        $module = $this->installableModules[$name];

        if (empty($module)) {
            throw new WireException();
        }

        $module->uninstall();

        return $module;
    }

    /**
     * Called when the URL is this module's page URL + "/install/?:name/"
     */
    public function ___executeInstall() {
        try {
            $module = $this->installModule(wire('input')->urlSegment(2));
        } catch (WireException $e) {
            header('Location:' . wire('pages')->get('template=admin, name=' . self::pageName)->url);
        }

        $this->message('Succesfully installed or updated ' . $module->name);

        $headline = 'Installing ' . $module->name;

        Wire::setFuel('processHeadline', $headline);

        $this->breadcrumbs->add(new Breadcrumb('../', self::$moduleInfo['title']));

        $outputTemplatePath = $this->templatePath . '/install.php';
        $outputTemplate = new TemplateFile($outputTemplatePath);
        $outputTemplate->setArray(array(
            'headline' => $headline,
            'installedFields' => $module->fields,
            'installedTemplates' => $module->templates,
            'installedPages' => $module->pages
        ));

        return $outputTemplate->render();

    }

    /**
     * Called when the URL is this module's page URL + "/uninstall/?:name/"
     */
    public function ___executeUninstall() {

        $this->breadcrumbs->add(new Breadcrumb('../', self::$moduleInfo['title']));

        $outputTemplatePath = $this->templatePath . '/uninstall.php';
        $outputTemplate = new TemplateFile($outputTemplatePath);

        try {

            $module = $this->uninstallModule(wire('input')->urlSegment(2));

            $headline = 'Uninstalling ' . $module->name;

            Wire::setFuel('processHeadline', $headline);

            $outputTemplate->setArray(array(
                'headline' => $headline,
                'deletedFields' => $module->deletedFields,
                'deletedTemplates' => $module->deletedTemplates,
                'deletedPages' => $module->deletedPages
            ));

        } catch (WireException $e) {
            $this->error($e->getMessage());
        }

        return $outputTemplate->render();

    }

    /**
     * Called when the URL is this module's page URL + "/confirm-uninstall/?:name/"
     */
    public function ___executeConfirmUninstall() {

        $out = '';

        $this->breadcrumbs->add(new Breadcrumb('../', self::$moduleInfo['title']));

        $this->loadModules();
        $name = wire('input')->urlSegment(2);

        $module = $this->installableModules[$name];

        if (empty($module)) {
            throw new WireException();
        }

        $module->uninstall($dryRun = true);

        $outputTemplatePath = $this->templatePath . '/confirm-uninstall.php';
        $outputTemplate = new TemplateFile($outputTemplatePath);

        $headline = 'Confirm uninstallation of ' . $module->name;
        $notInstalledYet = !$module->hasDeletableItems();

        Wire::setFuel('processHeadline', $headline);

        if (!$notInstalledYet) {
            $this->error('Warning: This feature is experimental.');
            $this->error('The uninstall process will try to delete all pages, templates and fields defined in this module json, so if you included directives to merely modify existing pages, templates or fields, you should add a "prefab" property to each of those and set it to "true".');
        }



        $outputTemplate->setArray(array(
            'headline' => $headline,
            'deletedFields' => $module->deletedFields,
            'deletedTemplates' => $module->deletedTemplates,
            'deletedPages' => $module->deletedPages,
            'notInstalledYet' => $notInstalledYet
        ));

        $out .= $outputTemplate->render();

        if (!$notInstalledYet) {
            $button = $this->modules->get('InputfieldButton');
            // $button->href = wire('pages')->get('template=admin, name=' . self::pageName)->url . '/' . $name;
            $button->href = $this->url . 'uninstall/' . $name;
            $button->value = 'Confirm';

            $out .= $button->render();
        }

        return $out;

    }

    public function ___install() {
        $page = new Page();
        $page->template = 'admin';
        $page->name = self::pageName;
        $page->parent = $this->pages->get($this->config->adminRootPageID)->child('name=setup');
        $page->process = $this;
        $page->title = 'JSON Installer';
        $page->save();

        $this->message('Created page: ' . $page->path);

        $this->installModule('config');
        $this->message('Ran config installation script');
    }

    public function ___uninstall() {
        $moduleID = $this->modules->getModuleID($this);
        $page = $this->pages->get('template=admin,process=' . $moduleID . ',name=' . self::pageName);

        if ($page->id) {
            $this->message('Deleting Page: ' . $page->path);
            $page->delete();
        }
    }
}
